language: python

matrix:
    include:
        - python: 3.7
            env: DJANGO_VERSION=3.2

        - python: 3.8
            env: DJANGO_VERSION=3.2

        - python: 3.8
            env: DJANGO_VERSION=4.0

        - python: 3.9
            env: DJANGO_VERSION=3.2

        - python: 3.9
            env: DJANGO_VERSION=4.0

        - python: 3.10
            env: DJANGO_VERSION=3.2

        - python: 3.10
            env: DJANGO_VERSION=4.0

before_install:
    - python --version
    - pip install -U pip
    - pip install -U pytest
    - pip install -U Django==$DJANGO_VERSION
    - pip install codecov
    - pip install coverage
    - pip install git+https://github.com/omise/omise-python@master
install:
    - pip install ".[test]" . # install package + test dependencies
script: coverage run run_tests.py # run tests
after_success:
    - codecov # submit coverage
