version: '3'

services:
    db:
        image: postgres:12
        user: postgres
        container_name: django_omise_db
        environment:
            - POSTGRES_DB=django_omise
            - POSTGRES_USER=django_omise
            - POSTGRES_PASSWORD=django_omise
        volumes:
            - django_omise_db:/var/lib/postgresql/data
        ports:
            - '5431:5432'
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready']
            interval: 10s
            timeout: 5s
            retries: 5
volumes:
    django_omise_db:
