# Generated by Django 3.2.13 on 2022-05-18 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("django_omise", "0001_squashed_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="first_digits",
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name="card",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="card",
            name="phone_number",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="card",
            name="postal_code",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="card",
            name="state",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="card",
            name="street1",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="card",
            name="street2",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="card",
            name="tokenization_method",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="source",
            name="flow",
            field=models.CharField(
                choices=[
                    ("redirect", "Redirect"),
                    ("offline", "Offline"),
                    ("app_redirect", "App Redirect"),
                ],
                help_text="The payment flow payers need to go through to complete the payment. One of redirect, offline, or app_redirect",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="type",
            field=models.CharField(
                choices=[
                    ("truemoney", "TrueMoney Wallet"),
                    ("internet_banking_bay", "Krungsri Bank"),
                    ("internet_banking_bbl", "Bangkok Bank"),
                    ("internet_banking_ktb", "Krungthai Bank"),
                    ("internet_banking_scb", "SCB Bank"),
                    ("promptpay", "Promptpay"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterModelOptions(
            name="event",
            options={},
        ),
        migrations.AddField(
            model_name="event",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="django_omis_content_80fefa_idx",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="object_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
