# Generated by Django 3.2.13 on 2022-05-17 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_omise', '0002_card_first_digits_card_name_card_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='flow',
            field=models.CharField(choices=[('redirect', 'Redirect'), ('offline', 'Offline'), ('app_redirect', 'App Redirect')], help_text='The payment flow payers need to go through to complete the payment. One of redirect, offline, or app_redirect', max_length=50),
        ),
        migrations.AlterField(
            model_name='source',
            name='type',
            field=models.CharField(choices=[('truemoney', 'TrueMoney Wallet'), ('internet_banking_bay', 'Krungsri Bank'), ('internet_banking_bbl', 'Bangkok Bank'), ('internet_banking_ktb', 'Krungthai Bank'), ('internet_banking_scb', 'SCB Bank'), ('promptpay', 'Promptpay')], max_length=255),
        ),
    ]
