# Generated by Django 3.2.13 on 2022-05-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_omise', '0004_auto_20220518_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='object_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
