# Generated by Django 3.2.13 on 2022-05-20 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_omise', '0006_chargeschedule_occurrence_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='django_omise.schedule'),
        ),
    ]
