# Generated by Django 3.2.13 on 2022-05-21 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_omise', '0008_alter_schedule_start_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end_on',
            field=models.DateField(blank=True, help_text='End date of schedule in ISO 8601 format.'),
        ),
    ]
