name: Release new version

on:
    release:
        types: [published]

concurrency:
    group: ${{ github.workflow }}

jobs:
    release-to-pypi:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v3
            - name: Install Python3.12.2
              uses: actions/setup-python@v5
              with:
                  python-version: '3.12.2'
            - name: Install poetry
              run: |
                  python -m pip install --user pipx
                  python -m pipx ensurepath
                  pipx install poetry
            - name: Install dependencies
              run: |
                  poetry install
            - name: Config pypi token
              run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN}}
            - name: Build and publish
              run: poetry publish --build
